version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule: 
    interval: "weekly"
    day: "saturday"
    time: "04:00"
    timezone: "Australia/Sydney"
- package-ecosystem: "cargo"
  directory: "/"
  schedule: 
    interval: "weekly"
    day: "saturday"
    time: "04:00"
    timezone: "Australia/Sydney"
